site_name: 追光的笔记本         
site_author: 追光          
site_url: https://note.zhuiguang.tech

repo_url: https://github.com/zhuiguang49/notebook
repo_name: zhuiguang49/notebook

theme:
  name: material
  language: zh  
  logo: assets/logo.png
  favicon: assets/logo.ico
  copyright: Copyright &copy; 2025 - 2026 <a href="https://github.com/zhuiguang49" target="_blank">zhuiguang</a>. All Rights Reserved.
  custom_dir: overrides              
  
  font:
    text: Roboto
    code: Roboto Mono

  palette:
    - scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式

    - scheme: slate
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式


  features:
    - navigation.tabs       
    - navigation.path                  
    - navigation.instant        
    - navigation.top            
    - header.autohide          
    - content.code.copy        
    - content.code.annotate  
    - search.suggest            
    - search.highlight
    - search.share

  social:
    - icon: fontawesome/brands/github   
      link: https://github.com/zhuiguang49
    - icon: fontawesome/solid/envelope
      link: mailto:zhuiguang49@foxmail.com         

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      lang: zh                   
  - git-revision-date-localized: 
      type: timeago
      locale: zh


extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-svg.js  


markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:         
      generic: true
  - pymdownx.highlight:       
      anchor_linenums: true
      line_spans: __span         
      pygments_lang_class: true   
  - pymdownx.inlinehilite        
  - pymdownx.snippets            
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format         
  - admonition                   
  - pymdownx.details             
  - pymdownx.tabbed:            
      alternate_style: true
  - attr_list                    
  - md_in_html                   



nav:
  - 'Home': 'index.md'
  - 'Computer Science':
    - 'OOP':
      - 'Week1 Using Object': 'CS/OOP/Week1 Using Object.md'
      - 'Week2 Grouping Object': 'CS/OOP/Week2 Grouping Object.md'
      - 'Week3 Class': 'CS/OOP/Week3 Class.md'
      - 'Week4&5 Inside Object': 'CS/OOP/Week4&5 Inside Object.md'
      - 'Week6 Inside Class': 'CS/OOP/Week6 Inside Class.md'
      - 'Week7 Composition': 'CS/OOP/Week7 Composition.md'
      - 'Week8 Inheritance': 'CS/OOP/Week8 Inheritance.md'
      - 'Week9 Polymorphism': 'CS/OOP/Week9 Polymorphism.md'
      - 'Week10 Copy and Move': 'CS/OOP/Week10 Copy and Move.md'
      - 'Week11 Overloaded Operator': 'CS/OOP/Week11 Overloaded Operator.md'
      - 'Week12 Template': 'CS/OOP/Week12 Template.md'
      - 'Week13 Exception': 'CS/OOP/Week13 Exception.md'
    - 'CS61B':  
      - 'Introduction': 'CS/CS61B/index.md'
      - 'Chapter1 Java Basics': 'CS/CS61B/Chapter1 Java Basic.md'
      - 'Chapter2 Lists': 'CS/CS61B/Chapter2 Lists.md'
      - 'Chapter3 OOP in Java': 'CS/CS61B/Chapter3 OOP in Java.md'
      - 'Chapter4 数据结构和算法概述': 'CS/CS61B/Chapter4 数据结构和算法概述.md'
      - 'Chapter5 并查集': 'CS/CS61B/Chapter5 并查集.md'
      - 'Chapter6 Tree': 'CS/CS61B/Chapter6 Tree.md'
      - 'Chapter7 Hash Table': 'CS/CS61B/Chapter7 Hash Table.md'
      - 'Chapter8 Heaps and Priority Queues': 'CS/CS61B/Chapter8 Heaps and Priority Queues.md'
      - 'Chapter9 Graph': 'CS/CS61B/Chapter9 Graph.md'
      - 'Chapter10 Graph Problems': 'CS/CS61B/Chapter10 Graph Problems.md'
      - 'Chapter11 Prefix Operations and Tries': 'CS/CS61B/Chapter11 Prefix Operations and Tries.md'
      - 'Chapter12 Sorting': 'CS/CS61B/Chapter12 Sorting.md'
    - 'ADS':
      - 'Lecture1 AVL Trees,Splay Trees and Amortized Analysis': 'CS/ADS/Lecture 1 AVL Trees,Splay Trees and Amortized Analysis.md'
      - 'Lecture2 Red-Black Trees and B+ Trees': 'CS/ADS/Lecture 2 Red-Black Trees and B+ Trees.md'
      - 'Lecture3 Inverted File Index': 'CS/ADS/Lecture 3 Inverted File Index.md'
      - 'Lecture4 Leftist Heaps and Skew Heaps': 'CS/ADS/Lecture 4 Leftist Heaps and Skew Heaps.md'
      - 'Lecture5 Binomial Queue': 'CS/ADS/Lecture5 Binomial Queue.md'


  - 'Math': 
    - '概率论': 
      - 'Chapter1 事件及其概率': 'Math/概率论/概率论笔记（第一章）.md'
      - 'Chapter2 随机变量与分布函数': 'Math/概率论/概率论笔记（第二章）.md'
      - 'Chapter3 数字特征与特征函数': 'Math/概率论/概率论笔记（第三章）.md'
      - 'Chapter4 极限定理': 'Math/概率论/概率论笔记（第四章）.md'
      - '极限定理': 'Math/概率论/极限定理.md'
  
    - '随机过程':
      - 'Chapter1 概率论复习': 'Math/随机过程/Chapter1 概率论复习.md'
      - 'Chapter2 随机过程的定义和分类': 'Math/随机过程/Chapter2 随机过程的定义和分类.md'
      - 'Chapter3 泊松过程': 'Math/随机过程/Chapter3 泊松过程.md' 
      - 'Chapter4 Markov链': 'Math/随机过程/Chapter4 Markov链.md'
      - 'Chapter5 分支过程': 'Math/随机过程/Chapter5 分支过程.md'
      - 'Chapter6 布朗运动': 'Math/随机过程/Chapter6 布朗运动.md'
      - 'Chapter7 平稳过程': 'Math/随机过程/Chapter7 平稳过程.md'   
    - '数学建模':
      - '数学建模备赛': 'Math/数学建模/数学建模准备.md'
    - '优化实用算法':
      - 'introduction': 'Math/优化实用算法/最优化方法（运筹学）.md'
      - '无约束优化':  
        - '无约束优化算法概述': 'Math/优化实用算法/Chapter1 无约束优化算法.md'
        - '线搜索方法': 'Math/优化实用算法/线搜索方法.md'
        - '梯度类算法': 'Math/优化实用算法/梯度类算法.md'
        - '牛顿类算法': 'Math/优化实用算法/牛顿类算法.md'
        - '共轭梯度法': 'Math/优化实用算法/共轭梯度法.md'
        - '信赖域方法': 'Math/优化实用算法/信赖域方法.md'
      - '非线性最小二乘问题':
        - '非线性最小二乘问题': 'Math/优化实用算法/非线性最小二乘问题.md'
      - '约束优化':
        - '约束优化最优性条件': 'Math/优化实用算法/约束优化最优性条件.md'
        - '线性规划': 'Math/优化实用算法/线性规划.md'
        - '二次规划': 'Math/优化实用算法/二次规划.md'
        - '罚函数法': 'Math/优化实用算法/罚函数法.md'
        - '增广拉格朗日函数法': 'Math/优化实用算法/增广拉格朗日函数法.md'